services:
  site1:
    image: nginx:stable-alpine
    volumes:
      - ./sites/site1:/usr/share/nginx/html:ro
    ports:
      - "8091:80"

  site2:
    image: nginx:stable-alpine
    volumes:
      - ./sites/site2:/usr/share/nginx/html:ro
    ports:
      - "8092:80"

  site3:
    image: nginx:stable-alpine
    volumes:
      - ./sites/site3:/usr/share/nginx/html:ro
    ports:
      - "8093:80"

  site4:
    image: nginx:stable-alpine
    volumes:
      - ./sites/site4:/usr/share/nginx/html:ro
    ports:
      - "8094:80"

  site5:
    image: nginx:stable-alpine
    volumes:
      - ./sites/site5:/usr/share/nginx/html:ro
    ports:
      - "8095:80"
